### ISSUE TITLE
Missing line to start the server

### ISSUE THREAD

**Issue by EhsanParsania** [dodi-smart/parse-server-typescript#74]
There is one line missing in the index.ts, which has caused an error:

![image](https://github.com/dodi-smart/parse-server-typescript/assets/75175231/e6b03be1-bcc9-42bf-832c-57c7e219b57d)

It is necessary to add `await parseServer.start();` in index.ts/line 15 and of course convert the function to an async function.

![Screenshot 2024-05-03 143041](https://github.com/dodi-smart/parse-server-typescript/assets/75175231/c7e936bd-e6ff-4168-94a7-fd758ab411e6)

**Comment by azlekov** [comment]
Hey, @EhsanParsania thanks for your contribution! 

Are you using this? If you find more improvements to suggests, feel free to open PRs or start a discussion. I stopped using Parse Server long ago, but still decided to leave this repo.
